### ISSUE TITLE
Housekeeping

### ISSUE THREAD

**Issue by kwabenantim** [jmsgrogan/cppwg#4]
**Description**
The  pybind11 template code and other TODO bits need updating.

**TODO**

- [x] Replace `PYBIND11_OVERLOAD` -> `PYBIND11_OVERRIDE` and `PYBIND11_OVERLOAD_PURE` -> `PYBIND11_OVERRIDE_PURE` : https://pybind11.readthedocs.io/en/stable/upgrade.html#v2-6
- [x] Replace `pyplusplus` in wrapper templates with `cppwg`.
- [x] Add `#include <pybind11/pybind11.h>` in wrapper hpp files and remove `namespace py = pybind11;`.
- [x] Remove unused code.
- [x] Return strings from generators rather than appending to input strings.
- [x] Fix TODOs in code.

**Comment by kwabenantim** [comment]
`PYBIND11_OVERLOAD` fixed in aa1d3474
